### ISSUE TITLE
Use parameterized types.

### ISSUE THREAD

**Issue by sixcorners** [BingAds/BingAds-Java-SDK#60] opened 2017-06-15 22:47 UTC
Why do types like ArrayOfKeywordPerformanceReportColumn exist? Couldn't that be ArrayOfReportColumn<KeywordPerformanceReportColumn> or just List<KeywordPerformanceReportColumn>?

**Comment by eric-urban** [comment] 2017-07-12 18:02
This helps with stronger type checking at compile time, as each report requires a specific column value set. These classes are auto [generated](https://github.com/BingAds/BingAds-Java-SDK/blob/master/proxies/generateAllServiceProxies.bat) directly from the Reporting service [WSDL](https://reporting.api.sandbox.bingads.microsoft.com/Api/Advertiser/Reporting/V11/ReportingService.svc?wsdl).

**Comment by sixcorners** [comment] 2017-07-12 19:49
I typed List&lt;KeywordPerformanceReportColumn&gt; but the stuff in the &lt;&gt; signs weren't displayed. Using List&lt;KeywordPerformanceReportColumn&gt; would be enough to restrict each list to a value set. If it's in the wsdl, is there a way that the wsdl could have represented these classes using parameterized types?
The ArrayOfKeywordPerformanceReportColumn seems like a wrapper that doesn't need to be there. It's like having a

    class TypeOfArrayOfKeywordPerformanceReportColumn {
        ArrayOfKeywordPerformanceReportColumn array;
    }
type.

**Comment by eric-urban** [comment] 2017-12-22 02:33
@sixcorners the current WSDL definitions are by design. I will go ahead and close this issue as there appear to be no blocking issues. For code samples please see [ReportRequests.java](https://github.com/BingAds/BingAds-Java-SDK/blob/master/examples/BingAdsDesktopApp/src/main/java/com/microsoft/bingads/examples/v11/ReportRequests.java).

**Closed by eric-urban** 2017-12-22 02:33 UTC
