### ISSUE TITLE
BulkServiceManager should delete its temp files

### ISSUE THREAD

**Issue by markus-s24** [BingAds/BingAds-Java-SDK#41] opened 2016-09-17 18:29 UTC
The BulkServiceManager should take care that all its temp files are deleted. 

Especially uploadEntitiesAsync() should delete its temp file after the upload request succeeded.
downloadEntitiesAsync() should return a BulkEntityIterable that deletes its underlying file on close().

I known that I can use cleanupTempFiles(), but that is no good option, because that tries to delete files generated by other BulkServiceManagers too.

**Comment by shyTNT** [comment] 2016-09-18 11:30
Thanks @markus-s24 . These temp files can track the state of uploading and downloading files. For example, the upload result file will record the error information for upload operation. So it is not very appropriate to delete all the temp files. To avoid deleting files generated by other BulkServiceManager, you can set **workingDirectory** for each BulkServiceManager and **cleanupTempFiles** will delete their own temp files.

**Comment by dennis-yemelyanov** [comment] 2016-09-18 17:55
Yes, as @shyTNT pointed out, initially we wanted to keep them to make troubleshooting easier on the client side, but deleting them automatically would also be useful for some scenarios. Maybe we can make this configurable by adding a flag cleanupTempFilesAutomatically to BulkServiceManager? For now we can set it to 'false' by default to keep existing behavior and think more about if we want to change the default for this setting later.

**Comment by markus-s24** [comment] 2016-09-18 19:49
Thanks @shyTNT for pointing out, that I can use a different temp dir for each BulkServiceManager instance. That helped me keeping my temp directories clean, though I need to write some cleanup code.

Anyway it would be nicer, if BulkServiceManager deletes them, if they are no longer used. That way I do not need to clean them up myself. I issued the PR https://github.com/BingAds/BingAds-Java-SDK/pull/42 that includes the suggested changes at least for the entity based upload and download methods. The on the fly created zip file, is not yet included in the automatic deletion.

As for the default for cleanupTempFilesAutomatically I would of suggest to set it to true, because setting it to false is just for debugging. But I won't be disappointed if this functionality makes it into BulkServiceManager with the default set to false ;-)

**Comment by dennis-yemelyanov** [comment] 2016-09-22 08:06
Thank you, Markus, for making this change. I'm fine to merge it, and we can probably set the default value to true in the next major update. Jianzhong, do you have any concerns?

**Comment by shyTNT** [comment] 2016-09-26 01:59
Thank you, @markus-s24. I'm fine to merge it too. And I think I will make this change work next month.

**Comment by shyTNT** [comment] 2016-09-29 08:52
Hi, @markus-s24. I tested your PR and  found that the BulkEntityIterable returned when upload/download entities can't go through the override method of close() in CSVBulkFileReaderFactory. This is because the override close() method is for BulkFileReader rather than the close() method in BulkEntityIterable.

**Comment by markus-s24** [comment] 2016-10-20 15:57
Sorry for the delay, I will redo the PR.

**Comment by markus-s24** [comment] 2016-10-24 13:52
See https://github.com/BingAds/BingAds-Java-SDK/pull/45

**Comment by eric-urban** [comment] 2017-03-24 04:04
Hi @markus-s24 

Just wanted to provide an update i.e. we tentatively plan to address this before end of June.

**Comment by eric-urban** [comment] 2017-08-08 13:36
Hi @markus-s24 

The team is actively evaluating and prototyping this update. However, we will not make it into this week's release. Will provide another update once we have a confirmed ETA.

**Comment by eric-urban** [comment] 2017-10-25 16:52
This is resolved with release [11.5.5](https://github.com/BingAds/BingAds-Java-SDK/releases/tag/v11.5.5). Please reach out if you find any issue.

**Closed by eric-urban** 2017-10-25 16:52 UTC
